### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JaakkoLipsanen** [JaakkoLipsanen/evento-web#7]
Not an priority atm (since not much real code yet :P) but we should try to keep coverage in the 80%-90% usually.

**Comment by anttilip** [comment]
We should mock server responses

**Comment by JaakkoLipsanen** [comment]
Also, figure out a way to mock react-router OR even better: figure out a way that no component depends on react-router. Now for example MainPage and TabContainer won't work if they are not inside <Router> element, and that's not good. If nothing else, then we should probably pass the router as a prop to all components that require it (= contains <Link> or <Router> etc)

**Comment by JaakkoLipsanen** [comment]
https://facebook.github.io/jest/docs/tutorial-async.html

http://www.wheresrhys.co.uk/fetch-mock/

Couple ways to mock networks requests.
